import express from "express";
import PDFDocument from "pdfkit";
import { requireAuth } from "./mw.js";
import AnalyticsReportRun from "../models/AnalyticsReportRun.js";
import {
  getOrgForRequest,
  requireFeatureAccess,
  sendGateFailure,
} from "../mw/featureGate.js";
import { loadAnalyticsPayload } from "./email_analytics.js";
import { sendBrandedEmail } from "../lib/mailer.js";

const router = express.Router();

function safeBranding(org = null) {
  const branding = org?.branding || {};
  return {
    orgName: org?.name || branding.org_name || "eStamp Pro",
    primaryColor:
  String(
    branding.primary_color ||
      branding.primaryColor ||
      org?.primary_color ||
      "#1d4ed8"
  ).trim() || "#1d4ed8",
    stampLabel: branding.stamp_label || "Official eStamp",
    logoUrl: branding.logo_url || "",
    websiteUrl: branding.website_url || "",
    supportEmail: branding.support_email || "",
    emailFooter:
      branding.email_footer ||
      "Confidential analytics report generated by eStamp Pro",
  };
}

function hexToRgb(hex) {
  const raw = String(hex || "").trim().replace("#", "");
  if (!/^[0-9a-fA-F]{6}$/.test(raw)) return [29, 78, 216];
  return [
    parseInt(raw.substring(0, 2), 16),
    parseInt(raw.substring(2, 4), 16),
    parseInt(raw.substring(4, 6), 16),
  ];
}

async function loadRemoteImageBuffer(url) {
  if (!url) return null;

  try {
    const res = await fetch(url);
    if (!res.ok) return null;

    const contentType = String(res.headers.get("content-type") || "").toLowerCase();
    if (
      !contentType.includes("png") &&
      !contentType.includes("jpg") &&
      !contentType.includes("jpeg")
    ) {
      return null;
    }

    const arr = await res.arrayBuffer();
    return Buffer.from(arr);
  } catch {
    return null;
  }
}

function drawHeader(doc, brand, days, logoBuffer = null) {
  const headerColor =
  brand.primaryColor &&
  /^#[0-9a-fA-F]{6}$/.test(String(brand.primaryColor))
    ? brand.primaryColor
    : "#1d4ed8";

doc.save();
doc.rect(0, 0, doc.page.width, 110).fill(headerColor);
doc.restore();
 
  const titleX = logoBuffer ? 120 : 40;

  if (logoBuffer) {
    try {
      doc.save();
      doc.roundedRect(40, 22, 58, 58, 10).fill("#ffffff");
      doc.restore();
      doc.image(logoBuffer, 42, 22, {
  fit: [64, 64],
});
    } catch {}
  }

  doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(28);
  doc.text(brand.orgName, titleX, 28, { width: 320 });

  doc.font("Helvetica").fontSize(13);
  doc.text(`Weekly Analytics Report · Last ${days} days`, titleX, 62);

  doc.fontSize(10).fillColor("#dbeafe");
  doc.text(`Stamp label: ${brand.stampLabel}`, titleX, 84);
}

function buildPdfBuffer(payload, brand, logoBuffer = null) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    const doc = new PDFDocument({ margin: 40, size: "A4" });

    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    console.log("REPORT BRANDING", brand);

    drawHeader(doc, brand, payload.days || 7, logoBuffer);
    doc.y = 125;

    const summary = payload.summary || {};

   doc.font("Helvetica-Bold")
  .fontSize(15)
  .fillColor("#0f172a")
  .text("Executive Summary");

const cards = [
  ["Sent", summary.sent ?? 0],
  ["Delivered", summary.delivered ?? 0],
  ["Opened", summary.opened ?? 0],
  ["Clicked", summary.clicked ?? 0],
  ["Failed", summary.failed ?? 0],
  ["Open Rate", `${summary.open_rate ?? 0}%`],
  ["Click Rate", `${summary.click_rate ?? 0}%`],
  ["Unique Opens", summary.unique_opened ?? 0],
  ["Unique Clicks", summary.unique_clicked ?? 0],
  ["Engagement", `${summary.engagement_score ?? 0}%`],
];

let cardX = 40;
let cardY = doc.y + 15;

const cardW = 155;
const cardH = 60;
const gap = 12;


cards.forEach(([label, value], index) => {
  if (index > 0 && index % 3 === 0) {
    cardX = 40;
    cardY += cardH + gap;
  }

 doc
  .roundedRect(cardX, cardY, cardW, cardH, 8)
  .fillAndStroke("#ffffff", "#cbd5e1");

doc
  .rect(cardX, cardY, cardW, 4)
  .fill(brand.primaryColor);

  doc
    .fillColor("#64748b")
    .fontSize(10)
    .text(label, cardX + 10, cardY + 10);

  doc
    .fillColor("#0f172a")
    .fontSize(24)
    .font("Helvetica-Bold")
    .text(String(value), cardX + 10, cardY + 28);

  cardX += cardW + gap;
});

const infoY = doc.y;

doc
  .roundedRect(40, infoY, 510, 60, 8)
  .fillAndStroke("#f8fafc", "#dbe4f0");

  doc.moveTo(210, infoY + 8)
   .lineTo(210, infoY + 52)
   .stroke("#dbe4f0");

doc.moveTo(380, infoY + 8)
   .lineTo(380, infoY + 52)
   .stroke("#dbe4f0");

doc
  .fillColor("#0f172a")
  .font("Helvetica-Bold")
  .fontSize(12)
  .text("Report Information", 52, infoY + 10);

doc
  .font("Helvetica")
  .fontSize(10)
  .text(`Organization: ${brand.orgName}`, 52, infoY + 28)
  .text(`Period: Last ${payload.days || 7} days`, 230, infoY + 28)
  .text(
    `Generated: ${new Date().toLocaleString("en-GB", {
      timeZone: "America/Grenada",
    })} AST`,
    400,
    infoY + 28
  );
  
doc.y = infoY + 80;
doc.moveDown();

    const docs = Array.isArray(payload.top_documents)
  ? payload.top_documents.slice(0, 10)
  : [];

doc
  .font("Helvetica-Bold")
  .fontSize(15)
  .fillColor("#0f172a")
  .text("Performance Leaders");

if (!docs.length) {
  doc
    .font("Helvetica")
    .fontSize(10)
    .fillColor("#64748b")
    .text("No document analytics available.");
} else {
  docs.forEach((d, idx) => {
    const startY = doc.y;
  
  doc
  .roundedRect(40, startY, 510, 48, 8)
  .fillAndStroke("#ffffff", "#dbe4f0");

doc
  .circle(70, startY + 24, 14)
  .fill(brand.primaryColor);

doc
  .fillColor("#ffffff")
  .font("Helvetica-Bold")
  .fontSize(11)
  .text(String(idx + 1), 66, startY + 19);

    doc
  .fillColor("#0f172a")
  .font("Helvetica-Bold")
  .fontSize(11)
  .text(
    `${d.subject || d.code || "Verification email"}`,
    100,
    startY + 8
  );

doc
  .fillColor("#475569")
  .font("Helvetica")
  .fontSize(9)
  .text(
    `Sent ${d.sent ?? 0} • Opened ${d.opened ?? 0} • Clicked ${d.clicked ?? 0} • Score ${d.score ?? 0}`,
    100,
    startY + 24
  );
    doc.y = startY + 58;
  });
}
doc.moveDown(2);

doc
  .font("Helvetica")
  .fontSize(8)
  .fillColor("#64748b")
  .text(
    brand.emailFooter ||
      "Generated by eStamp Pro Analytics",
    {
      align: "center",
    }
  );

if (brand.websiteUrl) {
  doc
    .fontSize(8)
    .fillColor("#1d4ed8")
    .text(brand.websiteUrl, {
      align: "center",
    });
}
    doc.end();
  });
}

function getAdminRecipients(org) {
  const reports = org?.report_settings || {};
  const configured = Array.isArray(reports.analytics_recipients)
    ? reports.analytics_recipients.filter(Boolean).map((v) => String(v).trim())
    : [];

  if (configured.length) return configured;

  if (org?.owner_email) return [String(org.owner_email).trim()];

  return [];
}

function normalizeSettingsPayload(body = {}) {
  return {
    analytics_reports_enabled: !!body.analytics_reports_enabled,
    analytics_report_frequency:
      String(body.analytics_report_frequency || body.frequency || "weekly").toLowerCase() === "weekly"
        ? "weekly"
        : "weekly",
    analytics_report_day: String(body.analytics_report_day || body.sendDay || "monday").toLowerCase(),
    analytics_recipients: Array.isArray(body.analytics_recipients)
      ? body.analytics_recipients.filter(Boolean).map((v) => String(v).trim())
      : typeof body.analytics_recipients === "string"
      ? body.analytics_recipients.split(",").map((v) => v.trim()).filter(Boolean)
      : Array.isArray(body.recipients)
      ? body.recipients.filter(Boolean).map((v) => String(v).trim())
      : typeof body.recipients === "string"
      ? body.recipients.split(",").map((v) => v.trim()).filter(Boolean)
      : [],
  };
}

/* ---------------- GET SETTINGS ---------------- */

router.get("/orgs/reports/settings", requireAuth, async (req, res) => {
  try {
    const org = await getOrgForRequest(req);

    if (!org) {
      return res.json({
        analytics_reports_enabled: false,
        analytics_report_frequency: "weekly",
        analytics_report_day: "monday",
        analytics_recipients: [],
        last_analytics_report_sent_at: null,
      });
    }

    const reports = org.report_settings || {};

    return res.json({
      analytics_reports_enabled: !!reports.analytics_reports_enabled,
      analytics_report_frequency: reports.analytics_report_frequency || "weekly",
      analytics_report_day: reports.analytics_report_day || "monday",
      analytics_recipients: reports.analytics_recipients || [],
      last_analytics_report_sent_at: reports.last_analytics_report_sent_at || null,
    });
  } catch (err) {
    console.error("report settings read error:", err);
    return res.status(500).json({ error: "Failed to load settings" });
  }
});

/* ---------------- SAVE SETTINGS ---------------- */

router.post("/orgs/reports/settings", requireAuth, async (req, res) => {
  try {
    const featureCheck = await requireFeatureAccess(req, "analytics");
    if (!featureCheck.ok) return sendGateFailure(res, featureCheck);

    const org = featureCheck.org;
    if (!org) {
      return res.status(404).json({ error: "Organization not found" });
    }

    const normalized = normalizeSettingsPayload(req.body || {});

    org.report_settings = {
      ...(org.report_settings || {}),
      analytics_recipients: normalized.analytics_recipients,
      analytics_reports_enabled: normalized.analytics_reports_enabled,
      analytics_report_frequency: normalized.analytics_report_frequency,
      analytics_report_day: normalized.analytics_report_day,
      last_analytics_report_sent_at:
        org.report_settings?.last_analytics_report_sent_at || null,
    };

    await org.save();

    return res.json({
      success: true,
      report_settings: org.report_settings,
    });
  } catch (err) {
    console.error("report settings save error:", err);
    return res.status(500).json({ error: err?.message || "Save failed" });
  }
});

/* ---------------- SEND NOW ---------------- */

router.post("/orgs/reports/send-now", requireAuth, async (req, res) => {
  let run = null;

  try {
    const featureCheck = await requireFeatureAccess(req, "analytics");
    if (!featureCheck.ok) return sendGateFailure(res, featureCheck);

    const org = featureCheck.org;
    if (!org) {
      return res.status(404).json({ error: "Organization not found" });
    }

    const recipients = getAdminRecipients(org);
    if (!recipients.length) {
      return res.status(400).json({
        error: "No analytics report recipients configured.",
      });
    }

    run = await AnalyticsReportRun.create({
      kind: "manual",
      org_id: org._id,
      org_name: org.name || "Unknown organization",
      status: "started",
      recipients,
      range_days: 7,
      subject: `${org.name || "Organization"} Weekly Analytics Report`,
      started_at: new Date(),
    });

    const payload = await loadAnalyticsPayload(String(org._id), 7);
    const brand = safeBranding(org);
    const logoBuffer = await loadRemoteImageBuffer(brand.logoUrl);
    const pdfBuffer = await buildPdfBuffer(payload, brand, logoBuffer);

    const html = `
      <div style="font-family:Arial,sans-serif;color:#0f172a">
        <h2 style="margin-bottom:8px">${brand.orgName} Weekly Analytics Report</h2>
        <p>Your weekly branded analytics report is attached.</p>
        <p>
          Sent: <strong>${payload.summary?.sent ?? 0}</strong> ·
          Opened: <strong>${payload.summary?.opened ?? 0}</strong> ·
          Clicked: <strong>${payload.summary?.clicked ?? 0}</strong>
        </p>
      </div>
    `;

    await sendBrandedEmail({
      to: recipients,
      subject: `${brand.orgName} Weekly Analytics Report`,
      html,
      text: `${brand.orgName} Weekly Analytics Report`,
      org,
      attachments: [
        {
          filename: "weekly-analytics-report.pdf",
          content: pdfBuffer,
          contentType: "application/pdf",
        },
      ],
    });

    org.report_settings = {
      ...(org.report_settings || {}),
      last_analytics_report_sent_at: new Date(),
    };
    await org.save();

    run.status = "sent";
    run.finished_at = new Date();
    run.meta = {
      summary: payload.summary || {},
      top_documents: payload.top_documents || [],
    };
    await run.save();

    return res.json({ success: true, run_id: run._id });
  } catch (err) {
    console.error("send now analytics report error:", err);

    if (run) {
      run.status = "failed";
      run.finished_at = new Date();
      run.error_message = err?.message || "Unknown error";
      await run.save().catch(() => {});
    }

    return res.status(500).json({
      error: err?.message || "Send failed",
    });
  }
});

/* ---------------- HISTORY ---------------- */

router.get("/orgs/reports/history", requireAuth, async (req, res) => {
  try {
    const org = await getOrgForRequest(req);

    if (!org) {
      return res.status(404).json({ error: "Organization not found" });
    }

    const rows = await AnalyticsReportRun.find({
      org_id: org._id,
    })
      .sort({ started_at: -1, createdAt: -1 })
      .limit(25)
      .lean();

    return res.json({ items: rows });
  } catch (err) {
    console.error("report history load error:", err);
    return res.status(500).json({ error: "Failed to load history" });
  }
});

export default router;