import express from "express";
import PDFDocument from "pdfkit";
import Organization from "../models/Organization.js";
import AnalyticsReportRun from "../models/AnalyticsReportRun.js";
import { loadAnalyticsPayload } from "./email_analytics.js";
import { sendOrgAnalyticsReport } from "../lib/mailer.js";

const router = express.Router();

function safeBranding(org = null) {
  const branding = org?.branding || {};
  return {
    orgName: org?.name || branding.org_name || "eStamp Pro",
    primaryColor: branding.primary_color || "#1d4ed8",
    stampLabel: branding.stamp_label || "Official eStamp",
    logoUrl: branding.logo_url || "",
    websiteUrl: branding.website_url || "",
    supportEmail: branding.support_email || "",
    emailFooter:
      branding.email_footer ||
      "Confidential analytics report generated by eStamp Pro",
  };
}

function hexToRgb(hex) {
  const clean = String(hex || "").replace("#", "").trim();
  if (!/^[0-9a-fA-F]{6}$/.test(clean)) return { r: 29, g: 78, b: 216 };
  return {
    r: parseInt(clean.slice(0, 2), 16),
    g: parseInt(clean.slice(2, 4), 16),
    b: parseInt(clean.slice(4, 6), 16),
  };
}

async function loadRemoteImageBuffer(url) {
  if (!url) return null;
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const contentType = String(res.headers.get("content-type") || "").toLowerCase();
    if (
      !contentType.includes("png") &&
      !contentType.includes("jpg") &&
      !contentType.includes("jpeg")
    ) {
      return null;
    }
    const arr = await res.arrayBuffer();
    return Buffer.from(arr);
  } catch {
    return null;
  }
}

function drawHeader(doc, brand, days, logoBuffer = null) {
  const { r, g, b } = hexToRgb(brand.primaryColor);

  doc.save();
  doc.rect(0, 0, doc.page.width, 108).fill(`rgb(${r},${g},${b})`);
  doc.restore();

  const titleX = logoBuffer ? 106 : 40;

  if (logoBuffer) {
    try {
      doc.save();
      doc.roundedRect(40, 22, 58, 58, 10).fill("#ffffff");
      doc.restore();
      doc.image(logoBuffer, 42, 24, { fit: [50, 50] });
    } catch {}
  }

  doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(24);
  doc.text(brand.orgName, titleX, 28, { width: 320 });

  doc.font("Helvetica").fontSize(12);
  doc.text(`Weekly Analytics Report · Last ${days} days`, titleX, 62);

  doc.fontSize(10).fillColor("#dbeafe");
  doc.text(`Stamp label: ${brand.stampLabel}`, titleX, 84);
}

function buildPdfBuffer(payload, brand, logoBuffer = null) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    const doc = new PDFDocument({ margin: 40, size: "A4" });

    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    drawHeader(doc, brand, payload.days || 7, logoBuffer);
    doc.y = 125;

    const summary = payload.summary || {};

    doc.font("Helvetica-Bold").fontSize(15).fillColor("#0f172a").text("Summary");
    doc.moveDown(0.4);

    [
      ["Sent", summary.sent ?? 0],
      ["Delivered", summary.delivered ?? 0],
      ["Opened", summary.opened ?? 0],
      ["Clicked", summary.clicked ?? 0],
      ["Failed", summary.failed ?? 0],
      ["Open rate", `${summary.open_rate ?? 0}%`],
      ["Click rate", `${summary.click_rate ?? 0}%`],
      ["Engagement score", `${summary.engagement_score ?? 0}%`],
    ].forEach(([label, value]) => {
      doc.font("Helvetica-Bold").fontSize(11).text(`${label}: `, { continued: true });
      doc.font("Helvetica").text(String(value));
    });

    doc.moveDown();

    doc.font("Helvetica-Bold").fontSize(15).text("Top performing documents");
    doc.moveDown(0.4);

    const docs = Array.isArray(payload.top_documents)
      ? payload.top_documents.slice(0, 10)
      : [];

    if (!docs.length) {
      doc.font("Helvetica").fontSize(10).fillColor("#64748b");
      doc.text("No document analytics available.");
    } else {
      docs.forEach((d, idx) => {
        doc.font("Helvetica-Bold").fontSize(11).fillColor("#0f172a");
        doc.text(`${idx + 1}. ${d.subject || d.code || "Verification email"}`);
        doc.font("Helvetica").fontSize(10).fillColor("#111827");
        doc.text(
          `Code: ${d.code ?? "—"} · Sent ${d.sent ?? 0} · Delivered ${d.delivered ?? 0} · Opened ${d.opened ?? 0} · Clicked ${d.clicked ?? 0} · Score ${d.score ?? 0}`
        );
        doc.moveDown(0.4);
      });
    }

    doc.end();
  });
}

function getTodayWeekdayUTC() {
  const weekdays = [
    "sunday",
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
  ];
  return weekdays[new Date().getUTCDay()];
}

function sameUtcDate(a, b) {
  if (!a || !b) return false;
  const da = new Date(a);
  const db = new Date(b);
  return (
    da.getUTCFullYear() === db.getUTCFullYear() &&
    da.getUTCMonth() === db.getUTCMonth() &&
    da.getUTCDate() === db.getUTCDate()
  );
}

function shouldSendToday(org) {
  const reports = org?.reports || {};
  if (!reports.analytics_reports_enabled) return false;

  const frequency = String(reports.analytics_report_frequency || "weekly").toLowerCase();
  if (frequency !== "weekly") return false;

  const configuredDay = String(reports.analytics_report_day || "monday").toLowerCase();
  const today = getTodayWeekdayUTC();

  if (configuredDay !== today) return false;
  if (sameUtcDate(reports.last_analytics_report_sent_at, new Date())) return false;

  return true;
}

function getRecipients(org) {
  const reports = org?.reports || {};
  const list = Array.isArray(reports.analytics_recipients)
    ? reports.analytics_recipients.filter(Boolean).map((v) => String(v).trim())
    : [];

  if (list.length) return list;
  if (org?.owner_email) return [String(org.owner_email).trim()];
  return [];
}

function isAuthorizedCronRequest(req) {
  const configured = String(process.env.CRON_SECRET || "").trim();
  if (!configured) return false;

  const authHeader = String(req.get("authorization") || "");
  const bearer = authHeader.startsWith("Bearer ") ? authHeader.slice(7).trim() : "";
  const headerSecret = String(req.get("x-cron-secret") || "").trim();

  return bearer === configured || headerSecret === configured;
}

router.post("/jobs/analytics-reports/run", async (req, res) => {
  try {
    if (!isAuthorizedCronRequest(req)) {
      return res.status(401).json({ error: "Unauthorized scheduler request." });
    }

    const orgs = await Organization.find({
      "reports.analytics_reports_enabled": true,
    });

    const results = {
      scanned: orgs.length,
      attempted: 0,
      sent: 0,
      skipped: 0,
      failed: 0,
      details: [],
    };

    for (const org of orgs) {
      let run = null;

      try {
        hasFeature(org, "analytics") 
        results.skipped++;
      
        if (!shouldSendToday(org)) {
          run = await AnalyticsReportRun.create({
            kind: "scheduled",
            org_id: org._id,
            org_name: org.name || "Unknown org",
            status: "skipped",
            reason: "Not scheduled for today or already sent today.",
            started_at: new Date(),
            finished_at: new Date(),
            range_days: 7,
          });

          results.skipped += 1;
          results.details.push({
            org_id: String(org._id),
            org_name: org.name || "Unknown org",
            status: "skipped",
            reason: run.reason,
          });
          continue;
        }

        const recipients = getRecipients(org);
        if (!recipients.length) {
          run = await AnalyticsReportRun.create({
            kind: "scheduled",
            org_id: org._id,
            org_name: org.name || "Unknown org",
            status: "skipped",
            reason: "No report recipients configured.",
            started_at: new Date(),
            finished_at: new Date(),
            range_days: 7,
          });

          results.skipped += 1;
          results.details.push({
            org_id: String(org._id),
            org_name: org.name || "Unknown org",
            status: "skipped",
            reason: run.reason,
          });
          continue;
        }

        results.attempted += 1;

        run = await AnalyticsReportRun.create({
          kind: "scheduled",
          org_id: org._id,
          org_name: org.name || "Unknown org",
          status: "started",
          recipients,
          range_days: 7,
          subject: `${org.name || "Organization"} Weekly Analytics Report`,
          started_at: new Date(),
        });

        const payload = await loadAnalyticsPayload(String(org._id), 7);
        const brand = safeBranding(org);
        const logoBuffer = await loadRemoteImageBuffer(brand.logoUrl);
        const pdfBuffer = await buildPdfBuffer(payload, brand, logoBuffer);

        const html = `
          <div style="font-family:Arial,sans-serif;color:#0f172a">
            <h2 style="margin-bottom:8px">${brand.orgName} Weekly Analytics Report</h2>
            <p>Your weekly branded analytics report is attached.</p>
            <p>
              Sent: <strong>${payload.summary?.sent ?? 0}</strong> ·
              Opened: <strong>${payload.summary?.opened ?? 0}</strong> ·
              Clicked: <strong>${payload.summary?.clicked ?? 0}</strong>
            </p>
          </div>
        `;

        await sendOrgAnalyticsReport({
          orgId: String(org._id),
          to: recipients,
          subject: `${brand.orgName} Weekly Analytics Report`,
          html,
          text: `${brand.orgName} Weekly Analytics Report`,
          pdfBuffer,
          filename: "weekly-analytics-report.pdf",
        });

        org.reports = org.reports || {};
        org.reports.last_analytics_report_sent_at = new Date();
        await org.save();

        run.status = "sent";
        run.finished_at = new Date();
        run.meta = {
          summary: payload.summary || {},
          top_documents: payload.top_documents || [],
        };
        await run.save();

        results.sent += 1;
        results.details.push({
          org_id: String(org._id),
          org_name: org.name || "Unknown org",
          status: "sent",
          recipients,
        });
      } catch (err) {
        if (run) {
          run.status = "failed";
          run.finished_at = new Date();
          run.error_message = err?.message || "Unknown error";
          await run.save().catch(() => {});
        } else {
          await AnalyticsReportRun.create({
            kind: "scheduled",
            org_id: org._id,
            org_name: org.name || "Unknown org",
            status: "failed",
            started_at: new Date(),
            finished_at: new Date(),
            range_days: 7,
            error_message: err?.message || "Unknown error",
          }).catch(() => {});
        }

        results.failed += 1;
        results.details.push({
          org_id: String(org._id),
          org_name: org.name || "Unknown org",
          status: "failed",
          error: err?.message || "Unknown error",
        });
      }
    }

    return res.json({ ok: true, ...results });
  } catch (err) {
    console.error("analytics scheduler error:", err);
    return res.status(500).json({ error: "Failed to run analytics scheduler." });
  }
});

export default router;