import express from "express";
import PDFDocument from "pdfkit";
import Organization from "../models/Organization.js";
import { requireAuth } from "./mw.js";
import { loadAnalyticsPayload } from "./email_analytics.js";
import { sendBrandedEmail } from "../lib/mailer.js";

const router = express.Router();

function safeBranding(org = null) {
  const branding = org?.branding || {};
  return {
    orgName: org?.name || branding.org_name || "eStamp Pro",
    primaryColor: branding.primary_color || "#1d4ed8",
    stampLabel: branding.stamp_label || "Official eStamp",
    logoUrl: branding.logo_url || "",
    websiteUrl: branding.website_url || "",
    supportEmail: branding.support_email || "",
    emailFooter:
      branding.email_footer ||
      "Confidential analytics report generated by eStamp Pro",
  };
}

function hexToRgb(hex) {
  const clean = String(hex || "").replace("#", "").trim();
  if (!/^[0-9a-fA-F]{6}$/.test(clean)) return { r: 29, g: 78, b: 216 };
  return {
    r: parseInt(clean.slice(0, 2), 16),
    g: parseInt(clean.slice(2, 4), 16),
    b: parseInt(clean.slice(4, 6), 16),
  };
}

async function loadRemoteImageBuffer(url) {
  if (!url) return null;
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const contentType = String(res.headers.get("content-type") || "").toLowerCase();
    if (!contentType.includes("png") && !contentType.includes("jpg") && !contentType.includes("jpeg")) {
      return null;
    }
    const arr = await res.arrayBuffer();
    return Buffer.from(arr);
  } catch {
    return null;
  }
}

function drawHeader(doc, brand, days, logoBuffer = null) {
  const { r, g, b } = hexToRgb(brand.primaryColor);

  doc.save();
  doc.rect(0, 0, doc.page.width, 108).fill(`rgb(${r},${g},${b})`);
  doc.restore();

  const titleX = logoBuffer ? 106 : 40;

  if (logoBuffer) {
    try {
      doc.save();
      doc.roundedRect(40, 22, 58, 58, 10).fill("#ffffff");
      doc.restore();
      doc.image(logoBuffer, 42, 24, { fit: [50, 50] });
    } catch {}
  }

  doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(24);
  doc.text(brand.orgName, titleX, 28, { width: 320 });

  doc.font("Helvetica").fontSize(12);
  doc.text(`Weekly Analytics Report · Last ${days} days`, titleX, 62);

  doc.fontSize(10).fillColor("#dbeafe");
  doc.text(`Stamp label: ${brand.stampLabel}`, titleX, 84);
}

function buildPdfBuffer(payload, brand, logoBuffer = null) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    const doc = new PDFDocument({ margin: 40, size: "A4" });

    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    drawHeader(doc, brand, payload.days || 7, logoBuffer);
    doc.y = 125;

    doc.font("Helvetica-Bold").fontSize(15).fillColor("#0f172a").text("Summary");
    doc.moveDown(0.4);

    const summary = payload.summary || {};
    [
      ["Sent", summary.sent ?? 0],
      ["Delivered", summary.delivered ?? 0],
      ["Opened", summary.opened ?? 0],
      ["Clicked", summary.clicked ?? 0],
      ["Failed", summary.failed ?? 0],
      ["Open rate", `${summary.open_rate ?? 0}%`],
      ["Click rate", `${summary.click_rate ?? 0}%`],
      ["Engagement score", `${summary.engagement_score ?? 0}%`],
    ].forEach(([label, value]) => {
      doc.font("Helvetica-Bold").fontSize(11).text(`${label}: `, { continued: true });
      doc.font("Helvetica").text(String(value));
    });

    doc.moveDown();
    doc.font("Helvetica-Bold").fontSize(15).text("Top performing documents");
    doc.moveDown(0.4);

    const docs = Array.isArray(payload.top_documents) ? payload.top_documents.slice(0, 10) : [];
    if (!docs.length) {
      doc.font("Helvetica").fontSize(10).fillColor("#64748b").text("No document analytics available.");
    } else {
      docs.forEach((d, idx) => {
        doc.font("Helvetica-Bold").fontSize(11).fillColor("#0f172a");
        doc.text(`${idx + 1}. ${d.subject || d.code || "Verification email"}`);
        doc.font("Helvetica").fontSize(10).fillColor("#111827");
        doc.text(
          `Code: ${d.code ?? "—"} · Sent ${d.sent ?? 0} · Delivered ${d.delivered ?? 0} · Opened ${d.opened ?? 0} · Clicked ${d.clicked ?? 0} · Score ${d.score ?? 0}`
        );
        doc.moveDown(0.4);
      });
    }

    doc.end();
  });
}

function getAdminRecipients(org) {
  const reports = org?.reports || {};
  const manual = Array.isArray(reports.analytics_recipients)
    ? reports.analytics_recipients.filter(Boolean)
    : [];

  if (manual.length) return manual;

  if (org?.owner_email) return [org.owner_email];

  return [];
}

router.get("/orgs/reports/settings", requireAuth, async (req, res) => {
  try {
    const org = await Organization.findById(req.user.orgId).lean();
    const reports = org?.reports || {};

    return res.json({
      analytics_reports_enabled: !!reports.analytics_reports_enabled,
      analytics_report_frequency: reports.analytics_report_frequency || "weekly",
      analytics_report_day: reports.analytics_report_day || "monday",
      analytics_recipients: reports.analytics_recipients || [],
      last_analytics_report_sent_at: reports.last_analytics_report_sent_at || null,
    });
  } catch (err) {
    console.error("report settings read error:", err);
    return res.status(500).json({ error: "Failed to load report settings" });
  }
});

router.post("/orgs/reports/settings", requireAuth, async (req, res) => {
  try {
    const {
      analytics_reports_enabled,
      analytics_report_frequency,
      analytics_report_day,
      analytics_recipients,
    } = req.body || {};

    const org = await Organization.findById(req.user.orgId);
    if (!org) return res.status(404).json({ error: "Organization not found" });

    org.reports = org.reports || {};
    org.reports.analytics_reports_enabled = !!analytics_reports_enabled;
    org.reports.analytics_report_frequency =
      analytics_report_frequency === "weekly" ? "weekly" : "weekly";
    org.reports.analytics_report_day = String(analytics_report_day || "monday").toLowerCase();
    org.reports.analytics_recipients = Array.isArray(analytics_recipients)
      ? analytics_recipients.filter(Boolean).map((v) => String(v).trim())
      : [];

    await org.save();

    return res.json({ ok: true, reports: org.reports });
  } catch (err) {
    console.error("report settings save error:", err);
    return res.status(500).json({ error: "Failed to save report settings" });
  }
});

router.post("/orgs/reports/send-now", requireAuth, async (req, res) => {
  try {
    const org = await Organization.findById(req.user.orgId);
    if (!org) return res.status(404).json({ error: "Organization not found" });

    const recipients = getAdminRecipients(org);
    if (!recipients.length) {
      return res.status(400).json({ error: "No analytics report recipients configured." });
    }

    const payload = await loadAnalyticsPayload(req.user.orgId, 7);
    const brand = safeBranding(org);
    const logoBuffer = await loadRemoteImageBuffer(brand.logoUrl);
    const pdfBuffer = await buildPdfBuffer(payload, brand, logoBuffer);

    const html = `
      <div style="font-family:Arial,sans-serif;color:#0f172a">
        <h2 style="margin-bottom:8px">${brand.orgName} Weekly Analytics Report</h2>
        <p>Your weekly branded analytics report is attached.</p>
        <p>
          Sent: <strong>${payload.summary?.sent ?? 0}</strong> ·
          Opened: <strong>${payload.summary?.opened ?? 0}</strong> ·
          Clicked: <strong>${payload.summary?.clicked ?? 0}</strong>
        </p>
      </div>
    `;

    await sendBrandedEmail({
      to: recipients,
      subject: `${brand.orgName} Weekly Analytics Report`,
      html,
      text: `${brand.orgName} Weekly Analytics Report`,
      attachments: [
        {
          filename: "weekly-analytics-report.pdf",
          content: pdfBuffer,
        },
      ],
      org,
    });

    org.reports = org.reports || {};
    org.reports.last_analytics_report_sent_at = new Date();
    await org.save();

    return res.json({ ok: true });
  } catch (err) {
    console.error("send now analytics report error:", err);
    return res.status(500).json({ error: "Failed to send analytics report" });
  }
});

export default router;