import express from "express";
import PDFDocument from "pdfkit";
import { requireAuth } from "./mw.js";
import { loadAnalyticsPayload } from "./email_analytics.js";
import Organization from "../models/Organization.js";

const router = express.Router();

function escCsv(value) {
  const s = String(value ?? "");
  if (/[",\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

function safeBranding(org = null) {
  const branding = org?.branding || {};
  return {
    orgName: org?.name || branding.org_name || "eStamp Pro",
    primaryColor: branding.primary_color || "#1d4ed8",
    accentColor: branding.accent_color || "#0f172a",
    stampLabel: branding.stamp_label || "Official eStamp",
    logoUrl: branding.logo_url || "",
    websiteUrl: branding.website_url || "",
    supportEmail: branding.support_email || "",
    emailFooter: branding.email_footer || "Confidential analytics report generated by eStamp Pro",
  };
}

function hexToRgb(hex) {
  const clean = String(hex || "").replace("#", "").trim();
  if (!/^[0-9a-fA-F]{6}$/.test(clean)) return { r: 29, g: 78, b: 216 };
  return {
    r: parseInt(clean.slice(0, 2), 16),
    g: parseInt(clean.slice(2, 4), 16),
    b: parseInt(clean.slice(4, 6), 16),
  };
}

function formatDateTime(value) {
  try {
    return new Date(value).toLocaleString();
  } catch {
    return String(value || "");
  }
}

function drawHeader(doc, brand, days) {
  const { r, g, b } = hexToRgb(brand.primaryColor);

  doc.save();
  doc.rect(0, 0, doc.page.width, 110).fill(`rgb(${r},${g},${b})`);
  doc.restore();

  doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(24);
  doc.text(brand.orgName, 40, 30, { width: 340 });

  doc.font("Helvetica").fontSize(12);
  doc.text(`Analytics Report · Last ${days} days`, 40, 62);

  doc.fontSize(10).fillColor("#dbeafe");
  doc.text(`Stamp label: ${brand.stampLabel}`, 40, 82);

  doc.fillColor("#ffffff")
    .font("Helvetica-Bold")
    .fontSize(16)
    .text("eStamp Pro", 420, 34, { align: "right", width: 130 });

  doc.font("Helvetica").fontSize(9).fillColor("#e2e8f0");
  doc.text(`Generated ${formatDateTime(new Date())}`, 390, 62, {
    align: "right",
    width: 160,
  });

  doc.moveDown();
}

function drawFooter(doc, brand) {
  const y = doc.page.height - 36;
  doc.save();
  doc.strokeColor("#e2e8f0").lineWidth(1);
  doc.moveTo(40, y - 8).lineTo(doc.page.width - 40, y - 8).stroke();
  doc.restore();

  doc.font("Helvetica").fontSize(8).fillColor("#64748b");
  doc.text(
    `${brand.emailFooter}${brand.websiteUrl ? ` · ${brand.websiteUrl}` : ""}${brand.supportEmail ? ` · ${brand.supportEmail}` : ""}`,
    40,
    y,
    { align: "center", width: doc.page.width - 80 }
  );
}

function drawSectionTitle(doc, title) {
  if (doc.y > 720) doc.addPage();
  doc.moveDown(0.6);
  doc.font("Helvetica-Bold").fontSize(14).fillColor("#0f172a").text(title);
  doc.moveDown(0.4);
}

function drawSummaryGrid(doc, summary) {
  const items = [
    ["Sent", summary.sent ?? 0],
    ["Delivered", summary.delivered ?? 0],
    ["Opened", summary.opened ?? 0],
    ["Clicked", summary.clicked ?? 0],
    ["Failed", summary.failed ?? 0],
    ["Open rate", `${summary.open_rate ?? 0}%`],
    ["Click rate", `${summary.click_rate ?? 0}%`],
    ["Unique opens", summary.unique_opened ?? 0],
    ["Unique clicks", summary.unique_clicked ?? 0],
    ["Unique open rate", `${summary.unique_open_rate ?? 0}%`],
    ["Unique click rate", `${summary.unique_click_rate ?? 0}%`],
    ["Engagement score", `${summary.engagement_score ?? 0}%`],
    ["Avg opens / email", summary.avg_opens_per_email ?? 0],
    ["Avg clicks / email", summary.avg_clicks_per_email ?? 0],
  ];

  const startX = 40;
  const startY = doc.y;
  const cols = 3;
  const boxW = 165;
  const boxH = 54;
  const gapX = 10;
  const gapY = 10;

  items.forEach(([label, value], i) => {
    const col = i % cols;
    const row = Math.floor(i / cols);
    const x = startX + col * (boxW + gapX);
    const y = startY + row * (boxH + gapY);

    doc.save();
    doc.roundedRect(x, y, boxW, boxH, 10).fillAndStroke("#f8fafc", "#dbe4f0");
    doc.restore();

    doc.font("Helvetica").fontSize(9).fillColor("#64748b");
    doc.text(String(label), x + 12, y + 10, { width: boxW - 24 });

    doc.font("Helvetica-Bold").fontSize(18).fillColor("#0f172a");
    doc.text(String(value), x + 12, y + 24, { width: boxW - 24 });
  });

  doc.y = startY + Math.ceil(items.length / cols) * (boxH + gapY) + 4;
}

function drawTopDocuments(doc, docs = []) {
  if (!docs.length) {
    doc.font("Helvetica").fontSize(10).fillColor("#64748b").text("No document analytics available.");
    return;
  }

  docs.slice(0, 12).forEach((d, idx) => {
    if (doc.y > 710) doc.addPage();

    doc.save();
    doc.roundedRect(40, doc.y, 515, 58, 10).fillAndStroke("#ffffff", "#e2e8f0");
    doc.restore();

    const y = doc.y + 8;

    doc.font("Helvetica-Bold").fontSize(11).fillColor("#0f172a");
    doc.text(`${idx + 1}. ${d.subject || d.code || "Verification email"}`, 52, y, {
      width: 360,
    });

    doc.font("Helvetica").fontSize(9).fillColor("#64748b");
    doc.text(`Code: ${d.code ?? "—"}`, 52, y + 16, { width: 220 });
    doc.text(`Score: ${d.score ?? 0}`, 430, y + 16, { width: 100, align: "right" });

    doc.font("Helvetica").fontSize(9).fillColor("#111827");
    doc.text(
      `Sent ${d.sent ?? 0} · Delivered ${d.delivered ?? 0} · Opened ${d.opened ?? 0} · Clicked ${d.clicked ?? 0}`,
      52,
      y + 31,
      { width: 300 }
    );
    doc.text(
      `Total opens ${d.total_opens ?? 0} · Total clicks ${d.total_clicks ?? 0}`,
      360,
      y + 31,
      { width: 170, align: "right" }
    );

    doc.y += 70;
  });
}

function drawTimelineTable(doc, timeline = []) {
  if (!timeline.length) {
    doc.font("Helvetica").fontSize(10).fillColor("#64748b").text("No timeline activity available.");
    return;
  }

  const rows = timeline.slice(-10);
  const startX = 40;
  let y = doc.y;

  const columns = [
    { label: "Date", x: startX, w: 110 },
    { label: "Sent", x: startX + 120, w: 60 },
    { label: "Delivered", x: startX + 190, w: 70 },
    { label: "Opened", x: startX + 270, w: 60 },
    { label: "Clicked", x: startX + 340, w: 60 },
    { label: "Failed", x: startX + 410, w: 60 },
  ];

  doc.save();
  doc.roundedRect(startX, y, 510, 24, 8).fill("#eff6ff");
  doc.restore();

  doc.font("Helvetica-Bold").fontSize(9).fillColor("#1e3a8a");
  columns.forEach((c) => doc.text(c.label, c.x + 8, y + 8, { width: c.w - 8 }));

  y += 30;

  rows.forEach((row) => {
    if (y > 720) {
      doc.addPage();
      y = 50;
    }

    doc.save();
    doc.roundedRect(startX, y, 510, 22, 6).fillAndStroke("#ffffff", "#e2e8f0");
    doc.restore();

    doc.font("Helvetica").fontSize(9).fillColor("#0f172a");
    doc.text(row.date || "—", columns[0].x + 8, y + 7, { width: columns[0].w - 8 });
    doc.text(String(row.sent ?? 0), columns[1].x + 8, y + 7, { width: columns[1].w - 8 });
    doc.text(String(row.delivered ?? 0), columns[2].x + 8, y + 7, { width: columns[2].w - 8 });
    doc.text(String(row.opened ?? 0), columns[3].x + 8, y + 7, { width: columns[3].w - 8 });
    doc.text(String(row.clicked ?? 0), columns[4].x + 8, y + 7, { width: columns[4].w - 8 });
    doc.text(String(row.failed ?? 0), columns[5].x + 8, y + 7, { width: columns[5].w - 8 });

    y += 28;
  });

  doc.y = y + 6;
}

router.get("/verify/share/analytics/export.csv", requireAuth, async (req, res) => {
  try {
    const payload = await loadAnalyticsPayload(req.user.orgId, req.query.days || 30);
    const docs = Array.isArray(payload.documents) ? payload.documents : [];

    const rows = [
      [
        "Code",
        "Subject",
        "Sent",
        "Delivered",
        "Opened",
        "Clicked",
        "Total Opens",
        "Total Clicks",
        "Unique Opens",
        "Unique Clicks",
        "Score",
        "Last Activity",
      ],
      ...docs.map((d) => [
        d.code ?? "",
        d.subject ?? "",
        d.sent ?? 0,
        d.delivered ?? 0,
        d.opened ?? 0,
        d.clicked ?? 0,
        d.total_opens ?? 0,
        d.total_clicks ?? 0,
        d.unique_opened ?? 0,
        d.unique_clicked ?? 0,
        d.score ?? 0,
        d.last_activity_at ?? "",
      ]),
    ];

    const csv = rows.map((row) => row.map(escCsv).join(",")).join("\n");

    res.setHeader("Content-Type", "text/csv; charset=utf-8");
    res.setHeader("Content-Disposition", `attachment; filename="email-analytics-${payload.days || 30}d.csv"`);
    return res.send(csv);
  } catch (err) {
    console.error("analytics csv export error:", err);
    return res.status(500).json({ error: "Failed to export analytics CSV" });
  }
});

router.get("/verify/share/analytics/export.pdf", requireAuth, async (req, res) => {
  try {
    const payload = await loadAnalyticsPayload(req.user.orgId, req.query.days || 30);
    const org = await Organization.findById(req.user.orgId).lean();
    const brand = safeBranding(org);

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="analytics-report-${payload.days || 30}d.pdf"`);

    const doc = new PDFDocument({ margin: 40, size: "A4", autoFirstPage: true });
    doc.pipe(res);

    drawHeader(doc, brand, payload.days || 30);
    doc.y = 125;

    drawSectionTitle(doc, "Summary");
    drawSummaryGrid(doc, payload.summary || {});

    drawSectionTitle(doc, "Top performing documents");
    drawTopDocuments(doc, payload.top_documents || payload.documents || []);

    drawSectionTitle(doc, "Recent timeline");
    drawTimelineTable(doc, payload.timeline || []);

    drawFooter(doc, brand);
    doc.end();
  } catch (err) {
    console.error("analytics pdf export error:", err);
    return res.status(500).json({ error: "Failed to export analytics PDF" });
  }
});

export default router;