import express from "express";
import multer from "multer";
import fs from "fs";
import { PDFDocument } from "pdf-lib";
import Audit from "../models/Audit.js";

const router = express.Router();
const upload = multer({ dest: "uploads/" });

function escapeHtml(str = "") {
  return String(str)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function renderPage({
  verified = false,
  code = "",
  stampId = "",
  documentId = "",
  timestamp = "",
  details = "",
}) {
  const badgeBg = verified ? "#dcfce7" : "#fee2e2";
  const badgeColor = verified ? "#166534" : "#991b1b";
  const badgeText = verified ? "Verified" : "Not Verified";

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>eStamp Pro Verification</title>
  <style>
    body {
      margin: 0;
      font-family: Arial, sans-serif;
      background: #f6f8fb;
      color: #1f2937;
    }
    .wrap {
      max-width: 720px;
      margin: 40px auto;
      padding: 24px;
    }
    .card {
      background: white;
      border: 1px solid #e5e7eb;
      border-radius: 16px;
      padding: 28px;
      box-shadow: 0 4px 14px rgba(0,0,0,0.06);
    }
    h1 {
      margin: 0 0 8px;
      font-size: 34px;
    }
    .sub {
      color: #6b7280;
      margin-bottom: 18px;
    }
    .badge {
      display: inline-block;
      padding: 8px 14px;
      border-radius: 999px;
      font-weight: 700;
      background: ${badgeBg};
      color: ${badgeColor};
      margin-bottom: 20px;
    }
    .grid {
      display: grid;
      grid-template-columns: 180px 1fr;
      gap: 10px 14px;
      margin-top: 16px;
    }
    .label {
      font-weight: 700;
      color: #374151;
    }
    .value {
      color: #111827;
      word-break: break-word;
    }
    .footer {
      margin-top: 24px;
      font-size: 13px;
      color: #6b7280;
    }
    .mono {
      font-family: Consolas, monospace;
    }
  </style>
</head>
<body>
  <div class="wrap">
    <div class="card">
      <h1>eStamp Pro</h1>
      <div class="sub">Public verification portal</div>

      <div class="badge">${badgeText}</div>

      <div class="grid">
        <div class="label">Verification Code</div>
        <div class="value mono">${escapeHtml(code || "—")}</div>

        <div class="label">Stamp ID</div>
        <div class="value mono">${escapeHtml(stampId || "—")}</div>

        <div class="label">Document ID</div>
        <div class="value mono">${escapeHtml(documentId || "—")}</div>

        <div class="label">Timestamp</div>
        <div class="value">${escapeHtml(timestamp || "—")}</div>

        <div class="label">Status Details</div>
        <div class="value">${escapeHtml(details || (verified ? "Stamp record found and verified." : "No matching verification record found."))}</div>
      </div>

      <div class="footer">
        This page was generated by eStamp Pro public verification.
      </div>
    </div>
  </div>
</body>
</html>
`;
}

// GET by verification code
router.get("/", async (req, res) => {
  try {
    const code = req.query.code || "";
    const wantsJson =
      req.query.format === "json" ||
      (req.headers.accept || "").includes("application/json");

    if (!code) {
      if (wantsJson) {
        return res.status(400).json({ error: "code_required" });
      }

      return res
        .status(400)
        .send(
          renderPage({
            verified: false,
            code: "",
            details: "Verification code is required.",
          })
        );
    }

    const audit = await Audit.findOne({
      "verification.payload.verify_code": code,
    })
      .sort({ createdAt: -1 })
      .lean();

    if (!audit) {
      if (wantsJson) {
        return res.status(404).json({
          verified: false,
          error: "not_found",
          code,
        });
      }

      return res
        .status(404)
        .send(
          renderPage({
            verified: false,
            code,
            details: "No matching stamp record was found for this verification code.",
          })
        );
    }

    const payload = audit?.verification?.payload || {};

    if (wantsJson) {
      return res.json({
        verified: true,
        source: "code",
        details: {
          stamp_id: audit.stamp_id,
          document_id: audit.document_id,
          timestamp: audit.createdAt || payload.ts || null,
          verification: audit.verification || null,
        },
      });
    }

    return res.send(
      renderPage({
        verified: true,
        code,
        stampId: String(audit.stamp_id || payload.stamp_id || ""),
        documentId: String(audit.document_id || payload.doc_id || ""),
        timestamp: String(audit.createdAt || payload.ts || ""),
        details: "Matching stamp audit record found.",
      })
    );
  } catch (e) {
    console.error("[verify_public GET] error", e);
    return res.status(500).send(
      renderPage({
        verified: false,
        code: req.query.code || "",
        details: "Verification failed due to a server error.",
      })
    );
  }
});

// POST by uploaded PDF (kept for API/manual testing)
router.post("/", upload.single("file"), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ error: "file_required" });
    }

    const pdfBytes = fs.readFileSync(req.file.path);

    try {
      await PDFDocument.load(pdfBytes);
    } catch {
      return res.status(400).json({ error: "invalid_pdf" });
    }

    const audit = await Audit.findOne({})
      .sort({ createdAt: -1 })
      .lean();

    if (!audit) {
      return res.status(404).json({
        verified: false,
        error: "no_stamp_found",
      });
    }

    return res.json({
      verified: true,
      source: "pdf",
      stamp_id: audit.stamp_id,
      document_id: audit.document_id,
      timestamp: audit.createdAt,
    });
  } catch (e) {
    console.error("[verify_public POST] error", e);
    return res.status(500).json({ error: "verify_failed" });
  } finally {
    if (req.file?.path) {
      try {
        fs.unlinkSync(req.file.path);
      } catch {}
    }
  }
});

export default router;
