import express from "express";
import Audit from "../models/Audit.js";

const router = express.Router();

function escapeHtml(str = "") {
  return String(str)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function renderPage({
  verified = false,
  code = "",
  stampId = "",
  documentId = "",
  timestamp = "",
  details = "",
}) {
  const badgeBg = verified ? "#dcfce7" : "#fee2e2";
  const badgeColor = verified ? "#166534" : "#991b1b";
  const badgeText = verified ? "Verified" : "Not Verified";

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>eStamp Pro Verification</title>
  <style>
    body {
      margin: 0;
      font-family: Arial, sans-serif;
      background: #f6f8fb;
      color: #1f2937;
    }
    .wrap {
      max-width: 760px;
      margin: 40px auto;
      padding: 24px;
    }
    .card {
      background: white;
      border: 1px solid #dbe4f0;
      border-radius: 16px;
      padding: 28px;
      box-shadow: 0 4px 14px rgba(0,0,0,0.06);
    }
    h1 {
      margin: 0 0 8px;
      font-size: 34px;
    }
    .sub {
      color: #6b7280;
      margin-bottom: 18px;
    }
    .badge {
      display: inline-block;
      padding: 8px 14px;
      border-radius: 999px;
      font-weight: 700;
      background: ${badgeBg};
      color: ${badgeColor};
      margin-bottom: 20px;
    }
    .grid {
      display: grid;
      grid-template-columns: 180px 1fr;
      gap: 10px 14px;
      margin-top: 16px;
    }
    .label {
      font-weight: 700;
      color: #374151;
    }
    .value {
      color: #111827;
      word-break: break-word;
    }
    .mono {
      font-family: Consolas, monospace;
    }
    .footer {
      margin-top: 24px;
      font-size: 13px;
      color: #6b7280;
    }
  </style>
</head>
<body>
  <div class="wrap">
    <div class="card">
      <h1>eStamp Pro</h1>
      <div class="sub">Public verification portal</div>

      <div class="badge">${badgeText}</div>

      <div class="grid">
        <div class="label">Verification Code</div>
        <div class="value mono">${escapeHtml(code || "—")}</div>

        <div class="label">Stamp ID</div>
        <div class="value mono">${escapeHtml(stampId || "—")}</div>

        <div class="label">Document ID</div>
        <div class="value mono">${escapeHtml(documentId || "—")}</div>

        <div class="label">Timestamp</div>
        <div class="value">${escapeHtml(timestamp || "—")}</div>

        <div class="label">Status Details</div>
        <div class="value">${escapeHtml(details || (verified ? "Stamp record found and verified." : "No matching verification record found."))}</div>
      </div>

      <div class="footer">
        This page was generated by eStamp Pro public verification.
      </div>
    </div>
  </div>
</body>
</html>
`;
}

router.get("/", async (req, res) => {
  try {
    const code = String(req.query.code || "").trim();
    const wantsJson =
      req.query.format === "json" ||
      (req.headers.accept || "").includes("application/json");

    if (!code) {
      if (wantsJson) {
        return res.status(400).json({ verified: false, error: "code_required" });
      }

      return res.status(400).send(
        renderPage({
          verified: false,
          details: "Verification code is required.",
        })
      );
    }

    const audit = await Audit.findOne({
      $or: [
        { verification_code: code },
        { "verification.payload.verify_code": code },
      ],
    })
      .sort({ created_at: -1 })
      .lean();

    if (!audit) {
      if (wantsJson) {
        return res.status(404).json({
          verified: false,
          error: "not_found",
          code,
        });
      }

      return res.status(404).send(
        renderPage({
          verified: false,
          code,
          details: "No matching stamp record was found for this verification code.",
        })
      );
    }

    const payload = audit?.verification?.payload || {};

    if (wantsJson) {
      return res.json({
        verified: true,
        source: "code",
        details: {
          stamp_id: audit.stamp_id || payload.stamp_id || null,
          document_id: audit.document_id || payload.doc_id || null,
          timestamp: audit.created_at || payload.ts || null,
          verification: audit.verification || null,
          meta: audit.meta || {},
        },
      });
    }

    return res.send(
      renderPage({
        verified: true,
        code,
        stampId: String(audit.stamp_id || payload.stamp_id || ""),
        documentId: String(audit.document_id || payload.doc_id || ""),
        timestamp: String(audit.created_at || payload.ts || ""),
        details: "Matching stamp audit record found.",
      })
    );
  } catch (e) {
    console.error("[verify_public GET] error", e);
    return res.status(500).send(
      renderPage({
        verified: false,
        code: req.query.code || "",
        details: "Verification failed due to a server error.",
      })
    );
  }
});

export default router;